builds:
  - 
   goos: 
     - freebsd
     - windows
     - linux
     - darwin
   goarch:
     - amd64
     - arm
     - arm64
     - '386'
   goarm:
     - 6
     - 7
archive:
  replacements:
    darwin: macOS 
    amd64: x86_64
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
